// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI only (migrate deploy on Vercel): use Neon's direct connection.
    // Through the pooler, migrate's pg_advisory_lock can be taken on one
    // backend and "released" on another, leaving it held and timing out
    // every later deploy (P1002). The app itself (lib/db.ts) stays pooled.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
